version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devOpsWorks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"

  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/devOpsWorks
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    depends_on:
      - db
